[module]
# Name of the module. (Required)
name = "x/slashing"

# Description of the module. (Optional)
description = "Slashing is responsible for reduce the voting power of a validator when they act maliciously."

# Link to where the module is located, it can also be a link to your project. (Optional)
homepage = "https://github.com/cosmos/cosmos-sdk"

#List of key words describing your module (Optional)
keywords = [
  "misbehaviour",
  "slashing",
]


[bug_tracker]
# A URL to a site that provides information or guidance on how to submit or deal
# with security vulnerabilities and bug reports.
url = "https://github.com/cosmos/cosmos-sdk/issues"

# To list multiple authors, multiple [[authors]] need to be created
[[authors]]
name = "alexanderbez"

[[authors]]
name = "fedekunze"

[[authors]]
name = "aaronc"

[version]
# The repository field should be a URL to the source repository for your module.
# Typically, this will point to the specific GitHub repository release/tag for the
# module, although this is not enforced or required. (Required)
repo = "https://github.com/cosmos/cosmos-sdk"

# The documentation field specifies a URL to a website hosting the module's documentation. (Optional)
documentation = "https://raw.githubusercontent.com/cosmos/cosmos-sdk/master/x/slashing/atlas/atlas-v0.41.x.md"

# The module version to be published. (Required)
version = "v0.41.x"

# An optional Cosmos SDK version compatibility may be provided. (Optional)
sdk_compat = "v0.41.x"
